apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::160885265516:role/eksctl-roboshop-dev-nodegroup-robo-NodeInstanceRole-SbfgbYSSoQvc
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainer
      userarn: arn:aws:iam::230989376808:user/saikumar
      username: saikumar

    - roboshop-trainer
      userarn: arn:aws:iam::230989376808:user/saikumar
      username: saikumar  
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-11T01:49:27Z"
  name: aws-auth
  namespace: kube-system
  uid: 33956aae-bab6-40e4-af5b-8e3b202d922e           